### PR TITLE
add istio release-1.0.5 required images

### PR DESCRIPTION
**Pull request by lenew**

### CODE REVIEW

**Comment by pahud** [comment]
Istio `release-1.0` actually needs `release-1.0-latest-daily` as the tag

https://github.com/istio/istio/blob/6eece306f065ea71fad07d9520d13fff35559d80/install/kubernetes/helm/istio/values.yaml#L9

Can you indicate where does it reauire `1.0.5` ?

**Comment by lenew** [comment]
Sorry for not verifying the image url.

I was trying install istio 1.0.5, but got this error
```
Failed to pull image "937788672844.dkr.ecr.cn-north-1.amazonaws.com.cn/gcr.io/istio-release/citadel:1.0.5": rpc error: code = Unknown desc = Error response from daemon: pull access denied for 937788672844.dkr.ecr.cn-north-1.amazonaws.com.cn/gcr.io/istio-release/citadel, repository does not exist or may require 'docker login'
```
I add 'gcr.io/istio-release/citadel:1.0.5' to images requirements list without confirm.

I'll do that change carefully next time.

**Comment by lenew** [comment]
Currently the values.yaml in v1.0.5 branch https://github.com/istio/istio/blob/1.0.5/install/kubernetes/helm/istio/values.yaml is different with the release package https://github.com/istio/istio/releases/download/1.0.5/istio-1.0.5-linux.tar.gz.

`release-1.0-latest-daily` in git branch
`1.0.5` in `istio-1.0.5-linux.tar.gz`

**Comment by lenew** [comment]
Aha, i figure out what's happening.
I should use docker.io instead of gcr.io. 
And install istio successfully **without** `--set global.hub=937788672844.dkr.ecr.cn-north-1.amazonaws.com.cn/gcr.io/istio-release`

**Comment by pahud** [comment]
@lenew can you share how to install isto 1.0.5 by specifying dockerhub as the repo?
I assue you still nee `--set global.hub` to somewhere?

**Comment by lenew** [comment]
@pahud No, just use it's default hub setting which is `docker.io/istio`.

**Pull request closed without merging**
